# Generated by Django 5.1.4 on 2024-12-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_milage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ['-year'], 'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
        migrations.AlterField(
            model_name='milage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milage', to='vehicle.car'),
        ),
    ]
